databases:
  - name: wasuremono_db
    databaseName: wasuremono_db
    user: wasuremono
    region: singapore

services:
  - type: web
    name: wasuremono
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: wasuremono_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

